// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvxxnqecndjrhldjqqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdnh4bnFlY25kanJobGRqcXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzQyMjUsImV4cCI6MjA1ODk1MDIyNX0.jaGSJ5xOv_YVaFEC_oheSNGK3-wMWxvaG4hTXVmuwbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);